/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SearchRouteImport } from './routes/search'
import { Route as MyListRouteImport } from './routes/my-list'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MediaTypeIdRouteImport } from './routes/$mediaType.$id'

const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const MyListRoute = MyListRouteImport.update({
  id: '/my-list',
  path: '/my-list',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MediaTypeIdRoute = MediaTypeIdRouteImport.update({
  id: '/$mediaType/$id',
  path: '/$mediaType/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/my-list': typeof MyListRoute
  '/search': typeof SearchRoute
  '/$mediaType/$id': typeof MediaTypeIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/my-list': typeof MyListRoute
  '/search': typeof SearchRoute
  '/$mediaType/$id': typeof MediaTypeIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/my-list': typeof MyListRoute
  '/search': typeof SearchRoute
  '/$mediaType/$id': typeof MediaTypeIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/my-list' | '/search' | '/$mediaType/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/my-list' | '/search' | '/$mediaType/$id'
  id: '__root__' | '/' | '/my-list' | '/search' | '/$mediaType/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MyListRoute: typeof MyListRoute
  SearchRoute: typeof SearchRoute
  MediaTypeIdRoute: typeof MediaTypeIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-list': {
      id: '/my-list'
      path: '/my-list'
      fullPath: '/my-list'
      preLoaderRoute: typeof MyListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$mediaType/$id': {
      id: '/$mediaType/$id'
      path: '/$mediaType/$id'
      fullPath: '/$mediaType/$id'
      preLoaderRoute: typeof MediaTypeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MyListRoute: MyListRoute,
  SearchRoute: SearchRoute,
  MediaTypeIdRoute: MediaTypeIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
